### ISSUE TITLE
Company as another filtering criteria for LC questions

### ISSUE THREAD

**Issue by mm1705** [SeanPrashad/leetcode-patterns#13]
Currently, `Companies` are shown for each problem. If we hover over the icon, the company name is displayed. 
How about when we hover over the company icon, we provide an option to click which results in a list of filtered LC questions for the current company? 
We may also change `Companies` to a dropdown like `Pattern` and `Difficulty`.

**Comment by SeanPrashad** [comment]
I think this would be pretty cool @mm1705 - I will have to play around with [react table](https://www.npmjs.com/package/react-table), the library I use to render the entire chart, to see if invoking a filter is possible via clicking an icon.

There are a handful of [simple and more complex examples](https://github.com/tannerlinsley/react-table/blob/HEAD/docs/examples.md) that would be a good starting point to see if this is possible.

**Comment by SeanPrashad** [comment]
Good news! It looks like this is possible:

![image](https://user-images.githubusercontent.com/13009507/83915522-68221b80-a741-11ea-9c16-1bb257426e6a.png)

There are some edge cases that I'm looking into. For example, when a company only has `hard` questions and the user had `easy` previously selected, it will show 0 questions (which is correct), but the filtering will not work properly for future selections.

**Comment by SeanPrashad** [comment]
Sweet - so I was able to get this working pretty nicely @mm1705! There were some edge cases with how the question list was being populated under certain criteria list [here](https://github.com/SeanPrashad/leetcode-patterns/issues/13#issuecomment-639745163) but I fixed it by always showing `Easy`, `Medium`, and `Hard` for the `Difficulty` dropdown, instead of populating dropdown list values based on a sorted collection of questions!

Please let me know if you run into any bugs/unintended side effects - thanks! ✌🏽
