### ISSUE TITLE
Random Problem Generation

### ISSUE THREAD

**Issue by doranmartinez** [seanprashad/leetcode-patterns#170]
Would be cool to have a button that randomly selected a problem to study.

**Comment by Shashank5665** [comment]
Hello there,
Can I please try to work on this issue?
I would like to contribute!

**Comment by seanprashad** [comment]
Hi @Shashank5665! Yes, please go ahead and let me know if you have any questions!

**Comment by seanprashad** [comment]
Hey @Shashank5665! 😁 I'm checking in to see how you're doing and if I can provide any help/suggestions?

**Comment by Shashank5665** [comment]
Hello @seanprashad 😃, I was able to successfully set up the project in my system. But, I was not familiar with react tables, useMemo, and a few other things in this project, and currently, my college exams are going on too😐. So, I was a bit busy with that.. but yeah I am in the process of learning react and I will definitely complete this once my exams are over, which will get over within 2 weeks or so.

**Comment by seanprashad** [comment]
> Hello @seanprashad 😃, I was able to successfully set up the project in my system. But, I was not familiar with react tables, useMemo, and a few other things in this project, and currently, my college exams are going on too😐. So, I was a bit busy with that.. but yeah I am in the process of learning react and I will definitely complete this once my exams are over, which will get over within 2 weeks or so. 

Okay sounds good! Don't hesitate to let me know if you need help, or if you'd like to open this up for another contributor. Good luck in your exams!

**Comment by Shashank5665** [comment]
Hello @seanprashad, My exams are over :D and I am continuing with the feature, I created a button that when clicked generates a random question, but I have made it such that it opens a new tab and takes the user to the leetcode site with the generated random question. I am finding it a bit difficult in understanding the Header and Cell cuz of which I am not getting how to render the generated question as a row.

**Comment by seanprashad** [comment]
> Hello @seanprashad, My exams are over :D and I am continuing with the feature, I created a button that when clicked generates a random question, but I have made it such that it opens a new tab and takes the user to the leetcode site with the generated random question. I am finding it a bit difficult in understanding the Header and Cell cuz of which I am not getting how to render the generated question as a row.

Sounds like you're making solid progress so far! Do you have a branch that we could take a look at? Feel free to open a "_Draft_" Pull Request - that would make it much easier for me to concretely point you in the right direction!

As far as `Header` and `Cell`, `Header` is the code that will generate the "first row" of the table where we have things like dropdown menus:

![Screenshot 2022-08-19 at 1 17 01 PM](https://user-images.githubusercontent.com/13009507/185672746-5c58d19c-ffb2-46f1-bdc5-40a2ec3e2240.jpg)

I think we could place the "_Random question_" button inside the `Header` section for `Questions`, aka right here: https://github.com/seanprashad/leetcode-patterns/blob/8d25c761f53e5e2bfcfa25f36d18e5e8a15fe0b4/src/components/Table/index.js#L235. Note that we'll need to add some JavaScript code to specify that "_We want to customize this header with a random question button_". We've actually already done this for the `Hide/Show Patterns` toggle - use it as a baseline for your work: https://github.com/seanprashad/leetcode-patterns/blob/8d25c761f53e5e2bfcfa25f36d18e5e8a15fe0b4/src/components/Table/index.js#L289-L309.

`Cell` is used to refer to the contents of each row - I don't think we'll need to edit the cell in this case, since we don't want the "_Randomize Question_" button to show up for each and every row!

Please let me know if anything is unclear - you've got this! 😁

**Comment by seanprashad** [comment]
Fixed with #240

**Comment by Shashank5665** [comment]
Thank you so much @doranmartinez for opening this issue, I was able to implement this feature with the help of @seanprashad 🙌
