### ISSUE TITLE
Feature request - Hide Patterns for Unsolved Problems

### ISSUE THREAD

**Issue by ishayadav181** [SeanPrashad/leetcode-patterns#25]
It would be great if we can hide topic tags for unsolved problems, knowing which algorithm to use beforehand restricts the thinking process in one direction.

**Comment by SeanPrashad** [comment]
Hey @ishayadav181 - I like this idea!

Originally when I had put together the list (and open sourced it as the website you see now), I thought that individuals could use it in a way to "learn" a pattern, like `Backtracking` and then continue on studying/solving other questions. In hindsight, I didn't think that some individuals would want to keep unsolved questions hidden..

Let me investigate some ways to go about this - stay tuned!

**Comment by ishayadav181** [comment]
Hi @SeanPrashad  
You are right some people may like to practice topic wise questions. Maybe an option like `Hide tags for unsolved problems` will do the work. Anyway thanks for your efforts. Nice problem set !

**Comment by SeanPrashad** [comment]
Hey @ishayadav181 - I had a toggle semi-working on a separate branch but there were some edge cases that I didn't fully understand (It's been awhile since I've worked in-depth with React).

As a workaround, patterns are now hidden by default, unless the respective checkbox has been checked - see below:

![Showing_Checked_Question ](https://user-images.githubusercontent.com/13009507/84206203-ad658680-aa7c-11ea-95bb-051d14a31d10.gif)

Please let me know if you run into any problems! ✌🏽
