### ISSUE TITLE
Feature request - Filter questions by company names

### ISSUE THREAD

**Issue by rishalshah** [SeanPrashad/leetcode-patterns#27]
Hi, it would be helpful if one could filter questions by clicking on company logo or having a search bar near the company header to search for questions asked by a particular company or a set of companies.

**Comment by SeanPrashad** [comment]
Hey @rishalshah! I had implemented this for a single company in https://github.com/SeanPrashad/leetcode-patterns/pull/21 - see below:

![image](https://user-images.githubusercontent.com/13009507/84203964-565db280-aa78-11ea-8ed5-0f09a4e83a15.png)

I think it would be possible to select multiple companies instead of just a single one but I'd have to look into it over the next bit!

**Comment by SeanPrashad** [comment]
Marking this as solved since there exists a dropdown list which individuals can use to filter questions by company.
